In [2]:
import numpy as np


In [4]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr1[:,2]  
#printing 3rd column 
arr1[:,1:3]
#printing column from 1 to 3 (meaning 1 and 2) 
arr1[2:4,1:3]
#results 2nd and 3rd row of 1st and 2nd column
arr1[4: , 2:]

array([[18, 19],
       [22, 23]])

In [22]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [23]:
for i in np.nditer(arr1):
    print(i)

#this fn prints each and every element of an np array

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
