In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low = 1, high = 100 , size = 20).reshape(4,5)
arr

array([[16, 11, 85,  1, 57],
       [10, 17,  6, 33, 23],
       [96, 22, 38,  2, 27],
       [67, 95, 12, 61, 81]])

In [6]:
arr>50
# results a boolean array
arr[arr>50] 
# here we overlapped the "arr" array from the condn arr>50 which means that elements which are >50 will only be present. This is known as "indexing using Boolean arrays"

array([85, 57, 96, 67, 95, 61, 81])

In [9]:
arr[(arr>50) & (arr%2!=0)]
# we use "& " with boolean values not "and"
arr[(arr>50) & (arr%2!=0)] = 0
arr

array([[16, 11,  0,  1,  0],
       [10, 17,  6, 33, 23],
       [96, 22, 38,  2, 27],
       [ 0,  0, 12,  0,  0]])