In [25]:
import numpy as np 


In [26]:
arr1 = np.array([1,2,3,4,5])
arr1.shape
arr1.ndim
arr1.size

5

In [27]:
type(arr1)

numpy.ndarray

In [28]:
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2)
arr2.shape
arr2.ndim
arr2.itemsize  #prints size of the datatype

[[1 2 3]
 [4 5 6]]


8

In [29]:
ar = np.array([[[1,2] ,
                 [3,4]], 

                 [[5,6] , 
                  [7,8]]])
print(ar)
ar.shape
ar.ndim
# ar.size
ar.itemsize

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


8

In [30]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# arr6 = np.arange(10)
# arr6
# arr7 = np.arange(5,15)
# arr7
arr8 = np.arange(5,15,2)
arr8


array([ 5,  7,  9, 11, 13])

In [34]:
arr9 = np.linspace(10,20,5)
arr9

array([10. , 12.5, 15. , 17.5, 20. ])

In [35]:
arr10 = arr9.copy()
arr10

array([10. , 12.5, 15. , 17.5, 20. ])

In [36]:
arr2.itemsize

8

In [38]:
ar.dtype 

dtype('int64')