In [1]:
import numpy as np

In [2]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
print(a1)
print(a2)



[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3,a4)
# print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [6]:
a3+a4
#in this the size of 2 arrays is diff. it implies that in this case each element of array a4 will be added to each element of a3 
# This is known as broadcasting  

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [9]:
a5 = np.arange(16).reshape(4,4)
a6 = np.arange(3).reshape(1,3)
print(a5,a6)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] [[0 1 2]]


In [10]:
a5+a6
#this wont be performed because these cant be broadcasted together.

ValueError: operands could not be broadcast together with shapes (4,4) (1,3) 