In [1]:
import numpy as np

In [10]:
np.random.random()

0.7448307373197209

In [15]:
np.random.seed(1)
np.random.random()
# we will get the same random value again & again


0.417022004702574

In [21]:
np.random.uniform(3,10)

4.303821479643696

In [23]:
np.random.uniform(1,100,10)
# 10 random values b/w 1 and 100

array([56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ,
       32.02899364, 69.53993895, 87.76252608, 89.56605969,  9.41937693])

In [32]:
np.random.randint(1,10,15).reshape(5,3)

array([[8, 8, 5],
       [6, 4, 7],
       [9, 1, 3],
       [8, 8, 8],
       [4, 1, 9]])

In [33]:
a = np.random.randint(1,10,6)
a

array([8, 8, 2, 2, 4, 1])

In [34]:
np.max(a)

np.int64(8)

In [36]:
np.argmax(a)
#index of max value in a 

np.int64(0)

In [37]:
a[np.argmax(a)]

np.int64(8)

In [41]:
a = np.random.randint(1,10,6)
a

array([6, 8, 9, 5, 5, 8])

In [42]:
a[a%2==1] = -1
a

array([ 6,  8, -1, -1, -1,  8])

In [43]:
# where(condn , true, false)
a = np.random.randint(1,50,6)
a


array([ 8, 46,  5, 49, 19, 33])

In [47]:
b = np.where(a%2==1 , -1 , a)
#in this case a new array is formed while in the above case changes were made in the same array
b

array([ 8, 46, -1, -1, -1, -1])

In [46]:
a

array([ 8, 46,  5, 49, 19, 33])

In [51]:
a = np.random.randint(1,50,10)
a

array([13,  2, 31, 42, 25, 19, 34,  3, 45, 29])

In [52]:
a = np.sort(a)
a

array([ 2,  3, 13, 19, 25, 29, 31, 34, 42, 45])

In [53]:
np.percentile(a,25)

np.float64(14.5)

In [54]:
np.percentile(a,50)

np.float64(27.0)

In [56]:
np.percentile(a,99.8)

np.float64(44.946)