In [1]:
import numpy as np


In [8]:
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([4,5,6,7,8,9])
ar1-ar2
ar1*ar2 #vector multiplication
ar1*2 #scalar multiplication


array([ 2,  4,  6,  8, 10, 12])

In [5]:
ar2>3


array([ True,  True,  True,  True,  True,  True])

In [20]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

arr3
arr4
arr3.dot(arr4)



array([[ 28,  31],
       [100, 112]])

In [26]:
arr4.max()
arr4.min()
arr4.min(axis = 0) #column wise minimum
arr4.min(axis = 1) # row wise min.
arr4.sum()
arr4.sum(axis = 0)
arr4.mean()
arr4.std()
np.sin(arr4)
np.median(arr4)


np.float64(8.5)

In [27]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [29]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
arr4.ndim

2

In [31]:
arr4.ravel()
# converts all the higher dimensional arrays into 1-D array

array([ 6,  7,  8,  9, 10, 11])

In [32]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [33]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [38]:
np.hstack((arr3,arr5))
#horizontal stacking joins 2 arrays
np.vstack((arr3,arr5))
#vertical stacking 


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [40]:
np.hsplit(arr3 , 3)


[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [41]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [42]:
arr8 = np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
arr8[[0,2,4]]
# what if we want 0th 2nd and 4th row since they are not continuous simple indexing wont help so we use fancy indexing here.

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])